[package]
name = "pelican_ui_messages"
version = "0.1.0"
edition = "2024"

[dependencies]
pelican_ui = {path = "../pelican_ui" }
pelican_ui_std = {path = "../pelican_ui_std" }
pelican_ui_profiles = {path = "../profiles" }
serde = "1.0.219"
